### ISSUE TITLE
Web Interface Error

### ISSUE THREAD

**Issue by The-Inamati** [r0hi7/DockerENT#35]
**Describe the bug**
When I try to run from the web interface it says 'NoneType' object is not subscriptable.

**To Reproduce**
1. Access the Web interface
2. Select all Containers, All Networks and All Tests
3. See error

**Expected behavior**
Tests to run I guess and some sort of feedback provided

**Screenshots**
![1](https://user-images.githubusercontent.com/45592340/94262070-c3635e00-ff2a-11ea-9754-366e6fabbe68.PNG)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser: Brave and Firefox

**Comment by r0hi7** [comment]
@The-Inamati  This issue has been fixed in the latest REL, can you specify the version of DockerENT you are using.

**Comment by The-Inamati** [comment]
I cloned the repo the same day I posted. The current version is v0.1.15

**Comment by r0hi7** [comment]
Just run `pip install DockerENT --upgrader` once to check if everything is
okay. I am running it, and it is running fine.

**Comment by r0hi7** [comment]
Closing this issue, please open if you feel this issue still exit.
